### ISSUE TITLE
IAM user policy statement action "ses:SendRawEmail" appears to have been deprecated in SESv2

### ISSUE THREAD

**Issue by simonallan** [charlesdotfish/smtp-credentials-cdk-construct#159]
Hi charlesdotfish.

Brief Issue Description:

The `ses:SendRawEmail` IAM policy action appears to have been have been deprecated in AWS SES version 2. This policy is applied to the user created by the 'createIamUser' construct and is causing an error when deploying our application, resulting in a failure to run the pipeline.

Expected Behaviour:

It is expected that the IAM Role Policy is created and applied, allowing the user to send emails.

Current Behaviour:

IAM Policy validator fails with warning: "Unrecognized actions - IAM does not recognize one or more actions. The action name might include a typo or might be part of a previewed or custom service." This leads to an error on deployment and initiates a rollback.

Possible Solution:

A possible solution may be to update the IAM action `ses:sendRawEmail` used in the `createIamUser` construct to `ses:sendEmail` action. This action is enabled in both SES and SESv2 and will not cause an error or warning from the validator.

Additional Information:

the `ses:sendRawEmail` action is more flexible and allows the sending of multipart MIME emails where the header can be set. I don't believe that this feature is being used in the `smtp-credentials-cdk-construct` and so should be safe to limit the allowed actions in the IAM Role Policy while also providing compatibility between SES and SESv2

Please feel free to reach out to me for any additional information.

Warm regards,
simonallan

**Comment by charles-salmon** [comment]
Hi @simonallan,

Thanks for raising this!

I've had a little bit of a play around this evening to see if I could replicate the issue that you're facing, but I unfortunately haven't had any luck. I may need some additional information before I can address this.

## Attempt to Replicate Issue

Firstly, I tried sending an email using the `aws sesv2 send-email` CLI, leveraging the identity created by an existing stack that I have, containing this construct. This email was sent successfully (with only the `ses:sendRawEmail` IAM action awarded to the identity).

Next, I destroyed an existing stack that leverages this construct, and recreated it. I was able to deploy an IAM policy containing the `ses:sendRawEmail` IAM action, and do not receive the same validation error that you received.

Can you potentially describe the context in which you received the IAM validation error message?

## Attempt to Leverage Suggested Solution

I tried rebuilding this package, leveraging the `ses:sendEmail` IAM action in place of the `ses:sendRawEmail` IAM action, and redeployed a stack that leverages this construct.

Using the SMTP settings found in the [AWS console](https://us-east-1.console.aws.amazon.com/ses/home?region=us-east-1#/smtp), in combination with the SMTP credentials created by this construct, I was unable to send an email.

When I attempted this, I received the following error message:

```
554 Access denied: User `arn:aws:iam::xxx:user/dev-charlesdotfish-Email-credentialsSmtpUser08EADD-1AP4CENXDBLXE' is not authorized to perform `ses:SendRawEmail' on resource `arn:aws:ses:us-east-1:xxx:identity/dev.charles.fish'
```

I was however able to send an email using the `aws sesv2 send-email` CLI.

Thanks,

Charles

**Comment by simonallan** [comment]
Hi Charles,

Apologies for the late reply on this, the team's developer has been away. I'm just the infrastructure engineer helping troubleshoot a pipeline issue that was preventing deployments.

For context, this issue materielaised as an error updating a CloudFormation stack while running the step in CodePipeline. Unfortunately with the fix in place the specific error message has been lost, the indication was that there was a problem with the SMTP user. First port of call was a quick check of the in-line policy via the console. The Visual Editor flagged the `SendRawEmail` action with a warning that this was unrecognised when used with SES v2. Screenshot from the production account that still shows the warning:

![IAMManagementConsole-2023-06-02 15_59_40](https://github.com/charlesdotfish/smtp-credentials-cdk-construct/assets/40426697/45bc529c-f235-4e23-8340-bdffda7384e7)

I manually updated this action to `SendEmail` in the development account and tested, successfully sending emails. The JSON for the policy matches that created by the `smtp-credentials-cdk-construct` so I figured you may want to know, hence raising the issue. As the `SendEmail` action is present for both SES and SES v2 I reasoned it would be fairly harmless, am surprised it broke things!

I'll catch-up with the developer and have a proper chat about what might be going on, will update this issue if anything comes up.

Thanks,
Simon

**Comment by simonallan** [comment]
I have made a terrible mistake! This is not the fix at all. My sincerest apologies.

Sorry for taking up your time, happy to close this issue.
